// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIE9TW6UFRE5SEaCDlSC0Bz5GemRMTyUM',
    appId: '1:227162368485:web:adf58735f60cfc236fa70c',
    messagingSenderId: '227162368485',
    projectId: 'attendance-b3683',
    authDomain: 'attendance-b3683.firebaseapp.com',
    storageBucket: 'attendance-b3683.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh4ExgKppPS-A2sHNmthk8XCedB1Ek2hA',
    appId: '1:227162368485:android:1bf287991aa641f46fa70c',
    messagingSenderId: '227162368485',
    projectId: 'attendance-b3683',
    storageBucket: 'attendance-b3683.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqP0dN30mwfRNfZgicYvAU8culHsi9TQQ',
    appId: '1:227162368485:ios:c5452c38c22fb0e36fa70c',
    messagingSenderId: '227162368485',
    projectId: 'attendance-b3683',
    storageBucket: 'attendance-b3683.firebasestorage.app',
    iosBundleId: 'com.example.management',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIE9TW6UFRE5SEaCDlSC0Bz5GemRMTyUM',
    appId: '1:227162368485:web:adf58735f60cfc236fa70c',
    messagingSenderId: '227162368485',
    projectId: 'attendance-b3683',
    authDomain: 'attendance-b3683.firebaseapp.com',
    storageBucket: 'attendance-b3683.firebasestorage.app',
  );

}